create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text not null,
  avatar_url text,
  bio text,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text,
  video_source text not null default 'demo',
  video_id text not null,
  thumbnail_url text,
  privacy text not null default 'friends' check (privacy in ('public', 'friends', 'invite')),
  status text not null default 'live' check (status in ('live', 'ended')),
  created_at timestamptz not null default now(),
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  is_active boolean not null default true,
  unique (session_id, user_id)
);

create table if not exists public.playback_state (
  session_id uuid primary key references public.sessions(id) on delete cascade,
  is_playing boolean not null default false,
  position double precision not null default 0,
  playback_rate double precision not null default 1,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

create index if not exists sessions_host_id_idx on public.sessions(host_id);
create index if not exists sessions_status_idx on public.sessions(status);
create index if not exists participants_session_active_idx on public.participants(session_id, is_active);

alter table public.profiles enable row level security;
alter table public.sessions enable row level security;
alter table public.participants enable row level security;
alter table public.playback_state enable row level security;

create policy "profiles are readable" on public.profiles for select using (true);
create policy "users manage own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);

create policy "public sessions are readable" on public.sessions for select using (privacy = 'public' or host_id = auth.uid());
create policy "users create own sessions" on public.sessions for insert with check (host_id = auth.uid());
create policy "hosts update own sessions" on public.sessions for update using (host_id = auth.uid()) with check (host_id = auth.uid());

create policy "participants can read their sessions" on public.participants for select using (user_id = auth.uid() or exists (select 1 from public.sessions s where s.id = session_id and s.host_id = auth.uid()));
create policy "users join sessions" on public.participants for insert with check (user_id = auth.uid());
create policy "users update own participation" on public.participants for update using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "participants read playback" on public.playback_state for select using (exists (select 1 from public.participants p where p.session_id = playback_state.session_id and p.user_id = auth.uid() and p.is_active));
create policy "host writes playback" on public.playback_state for insert with check (updated_by = auth.uid());
create policy "host updates playback" on public.playback_state for update using (updated_by = auth.uid() or exists (select 1 from public.sessions s where s.id = session_id and s.host_id = auth.uid())) with check (updated_by = auth.uid() or exists (select 1 from public.sessions s where s.id = session_id and s.host_id = auth.uid()));

-- Realtime is used by src/sync.ts for playback broadcasts.
-- For production, restrict private channels with Supabase Realtime authorization policies.
